name: CI - Wanderlust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      - name: Lint frontend
        run: |
          cd frontend
          yarn run lint

      - name: Build frontend
        run: |
          cd frontend
          yarn run build

      - name: Install backend dependencies
        run: |
          cd backend
          yarn install

      - name: Lint backend
        run: |
          cd backend
          npx eslint .

      - name: Install test framework (Mocha)
        run: |
          cd backend
          yarn add --dev mocha

      - name: Run backend tests
        run: |
          cd backend
          npx mocha test/**/*.js